import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './fonts.css'
import { Navbar } from './navbar'
import { RecipesNavbar } from './recipes-navbar'
import { ContentTopbar } from './content-topbar'
import { AppProviders } from '@/components/shared/providers'
import { unstable_cache } from 'next/cache'
import dbConnect from '@/lib/db/connect'
import { Product, ProductI } from '@/lib/models/product'
import { ProductsProvider } from '@/components/shared/products-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const getProducts = async () => {
  await dbConnect()
  const products = await Product.find<ProductI>({
    price: { $exists: true, $gt: 0 },
  }).lean()
  const p = JSON.parse(JSON.stringify(products))
  return p
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const products = await getProducts()
  return (
    <html lang='en'>
      <body className={inter.className + ' bg-background'}>
        <AppProviders>
          <ProductsProvider value={products}>
            <div className='flex h-screen relative overflow-hidden'>
              <div className='hidden lg:block'>
                <Navbar />
              </div>

              <main className='styled-scroll relative flex-1 h-full overflow-y-auto '>
                <ContentTopbar />
                {children}
              </main>
              <div className='hidden xl:block'>
                <RecipesNavbar />
              </div>
            </div>
          </ProductsProvider>
        </AppProviders>
      </body>
    </html>
  )
}
