import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './fonts.css'
import { Navbar } from './navbar'
import { RecipesNavbar } from './recipes-navbar'
import { ContentTopbar } from './content-topbar'
import { AppProviders } from '@/components/shared/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppProviders>
          <div className='flex h-screen relative overflow-hidden'>
            <div className='hidden lg:block'>
              <Navbar />
            </div>

            <div className='hidden xl:block'>
              <RecipesNavbar />
            </div>

            <main className='relative flex-1 h-full overflow-y-auto'>
              <ContentTopbar />
              {children}
            </main>
          </div>
        </AppProviders>
      </body>
    </html>
  )
}
